/** Inspection status for third-party exchange logic */

export const INSPECTION_STATUS = {
  PENDING: "PENDING",
  IN_PROGRESS: "IN_PROGRESS",
  OVERDUE: "OVERDUE",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
};

export const INSPECTION_STATUS_LABEL = {
  [INSPECTION_STATUS.PENDING]: "Pending",
  [INSPECTION_STATUS.IN_PROGRESS]: "In Progress",
  [INSPECTION_STATUS.OVERDUE]: "Overdue",
  [INSPECTION_STATUS.COMPLETED]: "Completed",
  [INSPECTION_STATUS.REJECTED]: "Rejected",
};

export const INSPECTION_STATUS_TAG_COLOR = {
  [INSPECTION_STATUS.PENDING]: "gold",
  [INSPECTION_STATUS.IN_PROGRESS]: "purple",
  [INSPECTION_STATUS.OVERDUE]: "red",
  [INSPECTION_STATUS.COMPLETED]: "green",
  [INSPECTION_STATUS.REJECTED]: "default",
};
